config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :events do 
    resources :reviews, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
  has_many :reviews
	belongs_to :host, :class_name => 'User', :foreign_key => 'user_id'
	has_many :reviewers, through: :reviews, source: :user

  validates :name, :location, :category, :price, :date, presence: true

  def self.search(search)
    if search
      @event = Event.find_by(date: search)
      if @event
        self.where(date: @event.date)
      else
        @events = Event.all
      end
    end
  end

  def self.upcoming
    where("date > ?", Time.now)
  end

  def self.past_event
    where("date < ?", Time.now)
  end

  def self.order_by_highest_price
    order(price: :desc)
  end

  def self.order_by_lowest_price
    order(price: :asc)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :user
  belongs_to :event

  validates :title, :content, presence: true

  def self.most_recent
    order(updated_at: :desc)
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :events
	has_many :reviews
	has_many :reviewed_events, through: :reviews, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  validates :username, presence: true, uniqueness: true

  def self.from_google(uid:, email:, full_name:, avatar_url:)
    if user = User.find_by(email: email)
      user.update(uid: uid, full_name: full_name, avatar_url: avatar_url) unless user.uid.present?
      user
    else
      User.create(
        email: email,
        uid: uid,
        full_name: full_name,
        avatar_url: avatar_url,
        password: SecureRandom.hex
      )
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
    
    def not_found
        flash[:error] = "Record not found / Unauthorized access"
        redirect_to root_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
    before_action :authenticate_user!
    before_action :set_event, only: [:edit, :update, :destroy]

    def index
        if @events = Event.search(params[:search])
            if @events == Event.all
            flash.now[:alert] = "No events found with that date."
            end
        else
            filter_options
        end
    end

    def show
        @event = Event.find(params[:id])
    end
    
    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to event_path(@event)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @event.update(event_params)
            redirect_to event_path(@event)
        else
            render :edit
        end
    end

    def destroy
        @event.destroy
        redirect_to events_path
    end

    private

    def set_event
        @event = current_user.events.find(params[:id])
    end

    def event_params
        params.required(:event).permit(:name, :category, :location, :price, :date, :search)
    end

    #goes in model
    def filter_options
        if params[:filter_by_date] == "upcoming"
            @events = Event.all.upcoming
        elsif params[:filter_by_date] == "past_event"
            @events = Event.all.past_event
        elsif params[:filter_by_date] == "my_events"
            @events = current_user.events
        else
            @events = Event.all
        end
        if params[:sort] == "order_by_lowest_price"
            @events = @events.order_by_lowest_price
        elsif params[:sort] == "order_by_highest_price"
            @events = @events.order_by_highest_price
        end
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_review, only: [:edit, :update, :destroy]

    def index
        @event = Event.find_by_id(params[:event_id])
        if @event
            @reviews = @event.reviews
        else
            sort_options
        end
    end

    def show
        @review = Review.find(params[:id])
    end

    def new
        @event = current_user.events.find_by_id(params[:event_id])
        if @event
            @review = @event.reviews.build
        else
            @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    def destroy
        @review.destroy
        redirect_to reviews_path
    end

    private

    def set_review
        @review = current_user.reviews.find(params[:id])
    end

    def review_params
        params.required(:review).permit(:title, :content, :user_id, :event_id)
    end

    def sort_options
        if params[:sort] == "updated_at"
            @reviews = Review.all.most_recent
        elsif params[:sort] == "my_reviews"
            @reviews = current_user.reviews
        else
            @reviews = Review.all
        end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def google_oauth2
        user = User.from_google(from_google_params)
        
        if user.present?
          sign_out_all_scopes
          flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect user, event: :authentication
        else
          flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
          redirect_to new_user_session_path
        end
      end
    
      protected
    
      def after_omniauth_failure_path_for(_scope)
        new_user_session_path
      end
    
      def after_sign_in_path_for(resource_or_scope)
        stored_location_for(resource_or_scope) || root_path
      end
    
      private
    
      def from_google_params
        @from_google_params ||= {
          uid: auth.uid,
          email: auth.info.email,
          full_name: auth.info.name,
          avatar_url: auth.info.image
        }
      end
    
      def auth
        @auth ||= request.env['omniauth.auth']
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
    def show_errors_for(object)
     render partial: 'shared/errors', locals: { object: object } 
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/events/_form.html.erb
<%= show_errors_for(@event) %>

<%= form_for @event do |f| %>
<p>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :category, "Category" %>
    <%= f.text_field :category %>
</p>
<p>
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
</p>
<p>
    <%= f.label :price, "Price" %>
    <%= f.number_field :price %>
</p>
<p>
    <%= f.label :date, "Date" %>
    <%= f.datetime_field :date %>
    <%= f.submit %>
</p>
<% end %>

app/views/events/edit.html.erb
<h1> Update Event </h1>

<%= render partial: 'form' %>

app/views/events/index.html.erb
<h1> Events </h1>

<% if user_signed_in? %>

  <div>
      <h3>Hello, <%= current_user.username %> </h3>
  </div>
  <%end %>
  
  <h4>Search by Date:</h4>
    <%= form_tag(events_path, method: :get) do %>
      <%= datetime_field_tag(:search, params[:search])%>
      <%= submit_tag ("Search") %>
    <% end %>

  <br>

<%= form_tag(events_path, method: 'get') do %>
  <label for="filter_by_date">Filter By</label>
  <select name="filter_by_date">
    <option <%= 'selected' if params[:filter_by_date] == '' %> value="">All</option>
    <option <%= 'selected' if params[:filter_by_date] == 'past_event' %> value="past_event">Past</option>
    <option <%= 'selected' if params[:filter_by_date] == 'upcoming' %> value="upcoming">Upcoming</option>
    <option <%= 'selected' if params[:filter_by_date] == 'my_events' %> value="my_events">My Events</option>
  </select>
  <label for="sort">Sort</label>
  <select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort] == 'order_by_lowest_price' %> value="order_by_lowest_price">Lowest Price</option>
    <option <%= 'selected' if params[:sort] == 'order_by_highest_price' %> value="order_by_highest_price">Highest Price</option>
  </select>
  <%= submit_tag 'Filter Results' %>
<% end %>
<br>
<button> <%= link_to 'New Event', new_event_path %> </button>

<% @events.each do |event| %>
<p> <%= link_to event.name, event_path(event) %> - $<%= event.price %></p>
<p>  When: <%= event.date.strftime('%A, %d %b %Y %l:%M %p') %> </p>
<% end %>

app/views/events/new.html.erb
<h1> New Event </h1>

<%= render partial: 'form' %>

app/views/events/show.html.erb
<h1> <%= @event.name %> </h1>

<h3> Time: <%= @event.date.strftime('%A, %d %b %Y %l:%M %p') %> </h3>
<h3> Location: <%= @event.location %> </h3>
<h3> Price: $ <%= @event.price %> </h3>
<h3> Category: <%= @event.category %> </h3>
<h3> By: <%= @event.host.username %> </h3>

<p> <%= link_to 'All Reviews', event_reviews_path(@event) %> </p>
<p> <%= link_to 'Add Review', new_event_review_path(@event) %> </p>

<p> <% if @event.user_id == current_user.id %> </p>
<p> <%= link_to 'Edit Event', edit_event_path(@event) %> </p>
<%= form_tag(event_path(@event), method: :delete) do %>
<%= submit_tag "Delete Event" %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <%= link_to 'Events', events_url %>
    <%= link_to 'Reviews', reviews_url %>
    <% if user_signed_in? %>
      <%= form_tag(destroy_user_session_path, method: :delete, style: 'display: inline-block' ) do %>
        <%= submit_tag "Sign Out" %>
      <% end %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
  </nav>
    
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= show_errors_for(@review) %>

<%= form_for @review do |f| %>
<p>
    <%= f.label :event_id, "Event Review" %>
    <%= f.collection_select :event_id, Event.all, :id, :name %>
</p>
<p>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :content, "Content" %>
    <%= f.text_field :content %>
</p>
    <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1> Update Review </h1>

<%= render partial: 'form' %>

app/views/reviews/index.html.erb
<h1> Reviews </h1>

<%= form_tag(reviews_path, method: 'get') do %>
  <label for="sort">Sort By</label>
  <select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">All</option>
    <option <%= 'selected' if params[:sort] == 'updated_at' %> value="updated_at">Most Recent</option>
    <option <%= 'selected' if params[:sort] == 'my_reviews' %> value="my_reviews">My Reviews</option>
  </select>
  <%= submit_tag 'Sort Results' %>
<% end %>
<br>
<button> <%= link_to 'Add Review', new_review_path %></button>

<% @reviews.each do |review| %>
<p> <%= link_to review.title, review_path(review) %> -<%= review.event.name %></p>
<p> by: <%= review.user.username %> </p>
<% end %>

app/views/reviews/new.html.erb
<h1> Add Review </h1>

<%= render partial: 'form' %>

app/views/reviews/show.html.erb
<h1> Review Details </h1>

<h3> Event: <%=  link_to  @review.event.name, event_reviews_path(@review.event) %></h3>
<h3> Title: <%= @review.title %> </h3>
<h3> Content: <%= @review.content %> </h3>
<h3> Review by: <%= @review.user.username %> </h3>

<p> <% if @review.user_id == current_user.id %> </p>
<p> <%= link_to 'Edit Review', edit_review_path(@review) %> </p>
<%= form_tag(review_path(@review), method: :delete) do %>
<%= submit_tag "Delete Review" %>
<% end %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class %> from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>